### ISSUE TITLE
Add "rls" command

### ISSUE THREAD

**Issue by parasyte** [rust-console/cargo-n64#4]
This command will allow running the `rls` server and passing default configuration options:

```toml
all_targets = false
sysroot = "/path/to/sysroot"
target = "/path/to/target.json"
```

Because it needs to pass absolute paths, the `target.json` should be created first, followed by `sysroot` with `cargo-xbuild`.

Bonus points if `all_targets` does not need to be disabled! This is required today because we don't have a `test` crate.
